### ISSUE TITLE
MediaWiki::Bot fails to log in

### ISSUE THREAD

**Issue by dertuxmalwieder** [MediaWiki-Bot/MediaWiki-Bot#77]
A few weeks ago, `MediaWiki::Bot` suddenly stopped to be able to log in.

Here's what I try:

    my $wikibot = MediaWiki::Bot->new(
      {
        protocol    => 'https',
        host        => 'de.wikipedia.org',
        path        => 'w',
        operator    => 'MyWikipediaNickname',
        login_data  => {
            username => "RechercheBot",
            password => $botpassword
        },
        debug       => 2
      }
    );

Well:

    Testing if logged in: we are (my IP), and we should be RechercheBot at /usr/local/libdata/perl5/site_perl/MediaWiki/Bot.pm line 2051.
    Couldn't log in with supplied settings at ./recherchebot.pl line 41.

Line 41 is the one starting with `my $wikibot`.

Manually logging in as RechercheBot (which is [a valid, not restricted account](http://de.wikipedia.org/wiki/Benutzer:RechercheBot)) with the supplied settings, however, works well. Do you have a clue?

**Comment by doherty** [comment]
When you say "manually logging in" do you mean calling the login method
directly, or logging in using your web browser?

Offhand, I don't know what the issue is. t/02-login.t and t/04-edit.t both
currently pass, which suggest that logging in does work.

**Comment by dertuxmalwieder** [comment]
Manually is over my web browser, yes. I'm confused.

**Comment by dertuxmalwieder** [comment]
Can I somehow help you track down the problem?

**Comment by bgwhite** [comment]
MediaWiki software changed login procedures.  My bot has been dead ever since the change.

See https://lists.wikimedia.org/pipermail/wikitech-l/2016-January/084501.html

**Comment by doherty** [comment]
I'm now spending zero time on non-maintainer tasks. Please feel free to fix
this and send a pull request. I'm happy to do code review, merges, and
releases, but I'm not doing development work on this project any longer.

**Comment by dertuxmalwieder** [comment]
That's bad news. :(

@bgwhite Do you have some time for that?

**Comment by bgwhite** [comment]
I do have time.  More importantly, I haven't a clue about cookie jars and
LWP::UserAgent.   Time to teach an old dog a new trick.

Bryan

**Comment by dertuxmalwieder** [comment]
`LWP::UserAgent` is greatly documented (although, if I had the chance, I'd switch over to Mojolicious; it's quite easier to use IMO). I can't help with cookie jars though; too many languages at a time ... but I'd gladly help where I can.

**Comment by guiwp** [comment]
I'm facing the same problem... :( 

About this issue as @doherty  said: "[...]I'm not doing development work on this project any longer.[...]". No one will submit pull request? If no, can anybody suggest another library that is actively maintained?

**Comment by dertuxmalwieder** [comment]
I guess there is none. So the only chance is to fork this and fix the issue.

**Comment by doherty** [comment]
If you're going to write a patch, just submit it here. I'm perfectly happy to accept patches and do releases.

**Comment by guiwp** [comment]
I'm trying to help but I'm not getting some things... (let me known if there is a forum that we can talk about this module)

I'm starting to learn Perl but I could see that your code is based on MediaWiki::API, and I don't known why but [the basic login sub works fine](https://metacpan.org/source/EXOBUZZ/MediaWiki-API-0.41/lib/MediaWiki/API.pm#L239).

Could you list please the features your login has that the other don't?

*  [basic auth](https://github.com/MediaWiki-Bot/MediaWiki-Bot/blob/f9a3ae1672b587f27bf90805ee506481d26a656a/lib/MediaWiki/Bot.pm#L441-L449)?
*  [load cookies from a file](https://github.com/MediaWiki-Bot/MediaWiki-Bot/blob/f9a3ae1672b587f27bf90805ee506481d26a656a/lib/MediaWiki/Bot.pm#L462-L473)?

Brad Jorsch (Anomie) said: 

["== For bots ==
You shouldn't notice any changes due to SessionManager, but do make sure
your code is **handling cookies normally instead of using the deprecated
return values from action=login to construct cookies manually**"](https://lists.wikimedia.org/pipermail/wikitech-l/2016-January/084501.html)

I just don't see in the code where is the "manual handling" (its not handled automatically by LWP module?)...

**Comment by wp-seth** [comment]
I still don't get the problem. I'm using MediaWiki::Bot v5.005006 (with MediaWiki::API v0.39 and LWP:UserAgent v6.05) at wmlabs without any login trouble. Which version do you use?

**Comment by dertuxmalwieder** [comment]
I can't log in on `de.wikipedia.org` with the newest Perl modules.

**Comment by wp-seth** [comment]
are you able to login if you use the versions I mentioned?

**Comment by dertuxmalwieder** [comment]
No success with MediaWiki::Bot v5.005006 and MediaWiki::API v0.39. Sadly, LWP::UserAgent v6.05 is 404 everywhere, so I'm stuck with the newest CPAN build.

**Comment by jlick** [comment]
MediaWiki 1.27 was recently released to the general public. According to the API documents, the login API has changed in this release: https://www.mediawiki.org/wiki/API:Login#How_to_log_in

I have a bot which maintains parts of the snpedia.com wiki. It was just upgraded to MediaWiki 1.27. Since then my bots have been unable to login. Functions which do not require authentication continue to work correctly.

The code which no longer works is:

$bot=MediaWiki::Bot->new({
        host    => 'bots.snpedia.com',
        path    => '',
        debug   => 1,
        protocol => 'https',
        operator => 'Jlick',
});

$bot->login({
        username => $username,
        password => $password,
        }) || die "Login failed.";

The errors are:

Error code 2: 500 Internal Server Error : error occurred when accessing https://bots.snpedia.com/api.php after 6 attempt(s) at /Desktop/DNA/bin/snpediapop.pl line 102.
Error code 2: 500 Internal Server Error : error occurred when accessing https://bots.snpedia.com/api.php after 6 attempt(s) at /Desktop/DNA/bin/snpediapop.pl line 102.
Error code 2: 500 Internal Server Error : error occurred when accessing https://bots.snpedia.com/api.php after 6 attempt(s) at /Desktop/DNA/bin/snpediapop.pl line 102.
Login failed. at /Desktop/DNA/bin/snpediapop.pl line 102.

The relevant modules are up to date as per what is in CPAN:

cpan[2]> install MediaWiki::API
MediaWiki::API is up to date (0.41).

cpan[3]> install MediaWiki::Bot
MediaWiki::Bot is up to date (5.006002).

cpan[4]> install LWP:UserAgent
LWP::UserAgent is up to date (6.15).

As this release also triggered end of support for MediaWiki 1.25, you may see a larger than usual number of people upgrading to the new version.

**Comment by guiwp** [comment]
_As of 1.27, the login action should only be used in combination with **bot passwords**, and clientlogin should be used by interactive applications._ [Login#How_to_log_in](https://www.mediawiki.org/wiki/API:Login#How_to_log_in)

I tested this new feature called "bot passwords" (just login your account and create a [bot password here](https://www.mediawiki.org/wiki/Special:BotPasswords)) and seems its working except that [_is_loggedin](MediaWiki-Bot/MediaWiki-Bot/blob/f9a3ae1672b587f27bf90805ee506481d26a656a/lib/MediaWiki/Bot.pm#L3506-L3513) is not working right. With my new account (username Guiwp@Wik) it says: 

`Testing if logged in: we are Guiwp, and we should be Guiwp@Wik at /home/guilherme/perl5/lib/perl5/MediaWiki/Bot.pm line 2051.`

Guiwp != Guiwp@Wik

**Comment by jlick** [comment]
Thanks, guiwp,

You solved my problem, or at least set me on the right path.

The Special:BotPasswords page seems to be specific to wikipedia sites.

From: http://permalink.gmane.org/gmane.science.linguistics.wikipedia.technical/85415

"If you need to continue using the existing action=login, ... go to Special:BotPasswords, set [a bot password] up, and then use new bot-password username and password to login as you've always done (no code changes, just update your bot's configuration)."

But Special:BotPasswords didn't work on the private wiki I use, and it goes on to explain:

"For bots that run on third-party wikis, Bot Passwords are in core and are
enabled by default."

This is about as clear as mud. I logged in on the web as my bot and poked around preferences for a bit, and got nowhere trying to find some place to set a bot password.

Then on a whim I decided to change my bot's regular login password. Suddenly my bot script could log in again. Changing the password accomplished whatever magic was required.

So the complete solution is:

On wikipedia foundation sites, go to the Special:BotPasswords page.
On private wikis, log into your bot account and change the password.

**Comment by dertuxmalwieder** [comment]
Hmm - so I gave my bot a bot password and changed the password to the one the particular page told me - still the same problem :(

**Comment by jlick** [comment]
Have you tried instead of setting username and password in login_data to use $wikibot->login as in my example?

**Comment by dertuxmalwieder** [comment]
That leaves me with "Login failed.". :-(

**Comment by doherty** [comment]
Should be fixed by 884f07d943f4fa48fbc5c48ed8399b8b37639b13

**Comment by dertuxmalwieder** [comment]
Hmm, I still get "Login failed. at ./recherchebot.pl line 52". Here's my code (line 52 ff):

    $wikibot->login({
      username => $botusername,
      password => $botpassword,
    }) || die "Login failed.";

`$botusername` is RechercheBot, the `$botpassword` is the generated password from the MediaWiki. Any hints?

**Comment by doherty** [comment]
When you created the bot password, you gave it a name. You should login
with the combined identifier "RechercheBot@name_of_bot_passwd" which was
displayed on the same page that showed you the generated bot password.
Otherwise, MediaWiki doesn't know to check that your using the bot
password, and instead checks against the regular password -- but you're not
allowed to use that to login.

**Comment by dertuxmalwieder** [comment]
Good point, thanks. Corrected it, but I still get *Login failed* with `'RechercheBot@RechercheBot'`...

**Comment by guiwp** [comment]
Here I don't see any problem, it's working right. Maybe you mistyped something.

**Comment by dertuxmalwieder** [comment]
Ah, yes - indeed. My "read from a password file" function didn't work as expected. Thank you, it works now!

**Comment by doherty** [comment]
Glad to hear it
